---
title: "Procedura testowa"
author: "Jakub Nowicki"
date: "23 listopada 2015"
output: pdf_document
---

# 1. Generacja modelowych populacji
  
Populacje powinny zostać stworzone przy pomocy funkcji `sample.population` (docelowo element pakietu `RetroGeomMorph`).

### `sample.population`
Generowanie sztucznej populacji obiektów

1. Parametry funkcji:

* model - liniowy model wieloparametrowy gdzie predyktorem jest wielkość centroidy (Csize). Generowany funkcją `generate.model`   
* population.size = 10 - liczebność generowanej populacji  
* Csize = c(10,100) - zakres wielkości centroidy w generowanej populacji 
* curves = NULL - matryca semilandmarków w postaci akceptowanej przez funkcję `geomorph::gpagen`  
* symmetry = FALSE - zastosowanie symetryzacji w generowanym zestawie (przy użyciu funkcji `morphoutils::symetria.2`); w przypadku kranidiów symetryzacja powinna być stosowana   
* mid = NULL - landmarki na linii symetrii w przypadku symetryzacji  
* left = NULL - przy symetryzacji landmarki lewej strony obiektu; numery landmarków muszą się zgadzać z numerami w danych potrzebnych do stworzenia modelu (tzn. jeżeli dane wyjściowe były symetryzowane funkcją `morphoutils::symetria.2`, to numery landmarków uległy zmianie!)  
* right = NULL - przy symetryzacji landmarki prawej strony obiektu; numeracja - patrz wyżej  
* random.sd = 0.0001 -   odchylenie standardowe parametru randomizująćego model liniowy
* elements = FALSE - użycie tego samego parametru randomizującego przy całych elementach obiektu (np. krawędź kranidium)  
* elements.list = NULL - lista elementów przy randomizacji (można wygenerować funkcją `split.list`)  

2. Wyjście

+ Sztuczna populacja o zadeklarowanym rozmiarze; format - lista podobna do tej tworzonej przez funkcję `geomorph::gpagen`

## Funkcje stosowane przy generacji sztucznych populacji

### `generate.predicted`  
Generowanie pojedynczego osobnika   

1. Parametry:  

+ model - liniowy model wieloparametrowy gdzie predyktorem jest wielkość centroidy (Csize). Generowany funkcją `generate.model`
+ predictor - wartość predyktora (wielkość centroidy)  
+ random.sd = 0.0001 - odchylenie standardowe parametru randomizująćego model liniowy  
+ elements = FALSE - użycie tego samego parametru randomizującego przy całych elementach obiektu (np. krawędź kranidium)   
+ elements.list = NULL - lista elementów przy randomizacji (można wygenerować funkcją `split.list`)  

2. Wyjście:  

+ matryca postaci `[1,x]` gdzie $x = 2*n.landmarków$

### `two.d.matrix`  
Zamiana wymiarów matrycy z [1,x] na [$x/2$,2]

1. Parametry:

+ data - matryca o wymmiarach [1,x]

2. Wyjście:

+ matryca w postaci [$x/2,2]

### `morphoutils::symetria.2`
Funkcja służąca symetryzacji badanego obiektu, oparta na funkcji `OSymm` stworzonej przez Annata Habera

1. Parametry:

+ dane - obiekt do symetryzacji
+ mid - landmarki na linii symetrii
+ left - landmarki lewej strony obiektu
+ right - landmarki prawej strony obiektu

2. Wyjście:

+ Obiekt po symetryzacji


### `generate.model`
Tworzenie modelu liniowego na podstawie superimpozowanego zestawu landmarków otrzymanego dzięki funkcji `geomorph::gpagen`

1. Parametry:

+ data - zestaw landmarków (wynik `geomorph::gpagen`)

2. Wyjście:

+ model liniowy z wielkością centroidy jako predyktorem

### `find.model.response.from.coeff`
Rozwiązuje równanie z jedną niewiadomą

1. Parametry:

+ interception - wyraz wolny równania
+ slope - współczynnik kierunkowy równania
+ x = NA - element x
+ y = NA - element y

2. Wyjście:

+ w przypadku podania w parametrach wartości x, funkcja zwraca y
+ w przypadku podania w parametrach wartości y, funkcja zwraca x

# 2. Deformacja populacji

Populacje mogą ulegać symulowanej deformacji tekonicznej.

### `deform.population`

Symuluje deformację tektoniczną populacji.

1. Parametry:

+ data - populacja do deformacji, postać typu uzyskiwanego z funkcji `geomorph::gpagen`
+ min.a = 0.8 - minimalny element ściskający
+ max.a = 1.2 - maksymalny element ściskający
+ min.theta = -0.5 - minimalny kąt działania ściskania
+ max.theta = 0.5 - maksymalny kąt działania ściskania
+ diff.elements = FALSE - wprowadza element losowy, wspólna, zrandomizowana deformacja wyznaczonych elementów
+ curves = NULL - krzywe, na podstawie których wyznaczone zostaną elementy
+ split.list = NULL - lista elementów, alternatywa dla wyznacznia elementów na podstawie krzywych
+ random.sd = NULL - odchylenie standardowe randomizowanej deformacji

2. Wyjście:

+ zdeformowana populacja w formacie `geomorph::gpagen`

## Funkcje stosowane przy symulowaniu deformacji tektonicznej

### `RetroGeoMorph::strain.matrix`

Tworzy matrycę odkształcenia.

1. Parametry:

+ a - odkształcenie
+ theta - kąt odkształcenia

2. Wyjście:

+ matryca odkształcenia

### `RetroGeoMorph::deformacja`

Deformuje zadany zestaw punktów zgodnie z podaną matrycą odkształcenia.

1. Parametry:

+ data - dane do deformowania
+ strain.matrix - matryca odkształcenia

2. Wyjście:

+ odkształcone dane

### `split.list`

Dzieli zestaw landmarków według elementów stworzonych na podstawie krzywych.

1. Parametry:

+ data - pojedynczy okaz obiektu do dzielenia
+ curves - matryca krzywych

2. Wyjście:

+ lista gdzie poszczególne elementy listy są zestawami landmarków w pojedynczym elemencie

### `find.elements`

Szuka serii landmarków lezących na współnych krzywych - łączy krzywe łączce się wspólnymi landmarkami.

1. Parametry:

+ curves - matryca krzywych

2. Wyjście:

+ lista elementów - serii landmarków

### `morphoutils::matrix.to.list`

Konwersja matrycy krzywych (semilandmarków) w postać listy.

1. Parametry:

+ curves - matryca krzywych
+ break.points - początki krzywych (numery wierszy w matrycy; wynik np. `morphoutils::find.curves`)

2. Wyjście:

+ krzywe w postaci listy

### `mophoutils::find.curves`

Znajduje początki krzywych w matrycy (numery wierszy)
.
1. Parametry:

+ curves - matryca krzywych

2. Wyjście:

+ począki krzywych (numery wierszy)

### `common.elements`

Sprawdza, czy dwa wektory mają wspólne elementy.

1. Parametry:

+ a - pierwszy wektor
+ b - drugi wektor

2. Wyjście:

+ wartość logiczna obecności wspólnych elementów

### `deform.elements`

Deformuje obiekt podzielony na elementy i wporwadza element losowych różnic w deformacji.

1. Parametry:

+ data - obiekt do deformacji
+ elements.list - lista numerów landmarków w poszczególnych elementach
+ a - odkształcenie
+ theta - kąt odkształcenia
+ random.sd - odchylenie standardowe przy randomizacji

1. Wyjście:

+ zdeformowany obiekt